/**
 * -------------------------------------------------------
 * Scenery Editor X
 * -------------------------------------------------------
 * Copyright (c) 2026 Thomas Ray
 * Copyright (c) 2026 Coalition of Freeware Developers
 * -------------------------------------------------------
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * -------------------------------------------------------
 * constants.slang
 * -------------------------------------------------------
 * Created: 07/03/2026
 * -------------------------------------------------------
 */
module constants;

public static const float PI = 3.14159265f;
public static const float PI2 = 6.28318530f;
public static const float PI4 = 12.5663706f;
public static const float INV_PI = 0.31830988f;
public static const float PI_HALF = PI * 0.5f;
public static const float FLT_MIN = 0.00000001f;
public static const float FLT_MAX_16 = 32767.0f;
public static const float FLT_MAX_16U = 65504.0f;
public static const float RPC_9 = 0.11111111111f;
public static const float RPC_16 = 0.0625f;
public static const float RPC_32 = 0.03125f;
public static const uint THREAD_GROUP_COUNT_X = 8;
public static const uint THREAD_GROUP_COUNT_Y = 8;
public static const uint THREAD_GROUP_COUNT = 64;
public static const float DEG_TO_RAD = PI / 180.0f;


