/**
 * -------------------------------------------------------
 * Scenery Editor X
 * -------------------------------------------------------
 * Copyright (c) 2026 Thomas Ray
 * Copyright (c) 2026 Coalition of Freeware Developers
 * -------------------------------------------------------
 * core.helpers.slang
 * -------------------------------------------------------
 * Stage 2 module implementation file for module `core`
 * -------------------------------------------------------
 */
implementing core;

import constants;
import resources;
import color;
import math;
import depth;
import common;
