/**
 * -------------------------------------------------------
 * Scenery Editor X
 * -------------------------------------------------------
 * Copyright (c) 2026 Thomas Ray
 * Copyright (c) 2026 Coalition of Freeware Developers
 * -------------------------------------------------------
 * lighting_lib.helpers.slang
 * -------------------------------------------------------
 * Stage 2 module implementation file for module `lighting_lib`
 * -------------------------------------------------------
 */
implementing lighting_lib;

import core;
import surface;
import brdf;
import shadow_mapping;
import fog;
import skysphere;
import lighting;
