/**
 * -------------------------------------------------------
 * Scenery Editor X
 * -------------------------------------------------------
 * Copyright (c) 2026 Thomas Ray
 * Copyright (c) 2026 Coalition of Freeware Developers
 * -------------------------------------------------------
 * pipeline.helpers.slang
 * -------------------------------------------------------
 * Stage 2 module implementation file for module `pipeline`
 * -------------------------------------------------------
 */
implementing pipeline;

import core;
import surface;
import lighting_lib;
