/**
 * -------------------------------------------------------
 * Scenery Editor X
 * -------------------------------------------------------
 * Copyright (c) 2026 Thomas Ray
 * Copyright (c) 2026 Coalition of Freeware Developers
 * -------------------------------------------------------
 * surface.helpers.slang
 * -------------------------------------------------------
 * Stage 2 module implementation file for module `surface`
 * -------------------------------------------------------
 */
implementing surface;

import core;
import structs;
import vertex_processing;
import tesselation;
