FUNCTION(SEDX_ENABLE_PCH target header)
    IF(TARGET ${target} AND EXISTS "${header}")
        IF(COMMAND TARGET_PRECOMPILE_HEADERS)
            MESSAGE(STATUS "Enabling PCH for ${target}")
            TARGET_PRECOMPILE_HEADERS(${target} PRIVATE ${header})
        ELSE()
            MESSAGE(STATUS "CMake Version is too old to use target_precompile_headers for ${target}")
        ENDIF()
    ENDIF()
ENDFUNCTION()
