if(DEFINED SEDX_PREFERRED_COMPILER)
    if(NOT (SEDX_PREFERRED_COMPILER STREQUAL "MSVC" OR SEDX_PREFERRED_COMPILER STREQUAL "CLANG_CL"))
        message(STATUS "Sanitizing global and target compile options for non-MSVC build (sanitize-msvc-flags.cmake)")
    else()
        return()
    endif()
else()
    if(NOT MSVC)
        message(STATUS "Sanitizing global and target compile options for non-MSVC build (sanitize-msvc-flags.cmake)")
    else()
        return()
    endif()
endif()

    set(_MSVC_TOKENS "/EHsc" "/Zc:preprocessor" "/GR")

    # Clean cached global flags
    foreach(_tok IN LISTS _MSVC_TOKENS)
        if(DEFINED CMAKE_CXX_FLAGS)
            string(REPLACE "${_tok}" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
            string(REPLACE "  " " " CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
            string(STRIP "${CMAKE_CXX_FLAGS}" CMAKE_CXX_FLAGS)
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}" CACHE STRING "" FORCE)
        endif()
        if(DEFINED CMAKE_C_FLAGS)
            string(REPLACE "${_tok}" "" CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
            string(REPLACE "  " " " CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
            string(STRIP "${CMAKE_C_FLAGS}" CMAKE_C_FLAGS)
            set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}" CACHE STRING "" FORCE)
        endif()
    endforeach()

    # Clean directory compile options
    get_property(_dirs DIRECTORY ${CMAKE_SOURCE_DIR} PROPERTY SUBDIRECTORIES)
    list(APPEND _dirs "${CMAKE_SOURCE_DIR}")
    foreach(_dir IN LISTS _dirs)
        if(EXISTS "${_dir}/CMakeLists.txt")
            get_property(_opts DIRECTORY ${_dir} PROPERTY COMPILE_OPTIONS)
            if(_opts)
                foreach(_tok IN LISTS _MSVC_TOKENS)
                    list(REMOVE_ITEM _opts "${_tok}")
                endforeach()
                # also remove tokens embedded inside options
                set(_clean_opts "")
                foreach(_o IN LISTS _opts)
                    set(_s "${_o}")
                    foreach(_tok IN LISTS _MSVC_TOKENS)
                        string(REPLACE "${_tok}" "" _s "${_s}")
                    endforeach()
                    string(STRIP "${_s}" _s)
                    if(NOT "${_s}" STREQUAL "")
                        list(APPEND _clean_opts "${_s}")
                    endif()
                endforeach()
                set_property(DIRECTORY ${_dir} PROPERTY COMPILE_OPTIONS "${_clean_opts}")
            endif()
        endif()
    endforeach()

    # Clean target compile options for all targets
    get_property(_all_targets GLOBAL PROPERTY TARGETS)
    foreach(_t IN LISTS _all_targets)
        if(TARGET ${_t})
            # COMPILE_OPTIONS
            get_target_property(_opts ${_t} COMPILE_OPTIONS)
            if(_opts)
                foreach(_tok IN LISTS _MSVC_TOKENS)
                    list(REMOVE_ITEM _opts "${_tok}")
                endforeach()
                set(_clean_opts "")
                foreach(_o IN LISTS _opts)
                    set(_s "${_o}")
                    foreach(_tok IN LISTS _MSVC_TOKENS)
                        string(REPLACE "${_tok}" "" _s "${_s}")
                    endforeach()
                    string(STRIP "${_s}" _s)
                    if(NOT "${_s}" STREQUAL "")
                        list(APPEND _clean_opts "${_s}")
                    endif()
                endforeach()
                if(_clean_opts)
                    set_target_properties(${_t} PROPERTIES COMPILE_OPTIONS "${_clean_opts}")
                endif()
            endif()

            # INTERFACE_COMPILE_OPTIONS
            get_target_property(_iopts ${_t} INTERFACE_COMPILE_OPTIONS)
            if(_iopts)
                foreach(_tok IN LISTS _MSVC_TOKENS)
                    list(REMOVE_ITEM _iopts "${_tok}")
                endforeach()
                set(_clean_iopts "")
                foreach(_o IN LISTS _iopts)
                    set(_s "${_o}")
                    foreach(_tok IN LISTS _MSVC_TOKENS)
                        string(REPLACE "${_tok}" "" _s "${_s}")
                    endforeach()
                    string(STRIP "${_s}" _s)
                    if(NOT "${_s}" STREQUAL "")
                        list(APPEND _clean_iopts "${_s}")
                    endif()
                endforeach()
                if(_clean_iopts)
                    set_target_properties(${_t} PROPERTIES INTERFACE_COMPILE_OPTIONS "${_clean_iopts}")
                endif()
            endif()
        endif()
    endforeach()

